name: Initial OpenWrt Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  trigger:
    uses: ./.github/workflows/build-x86-64.yml
    with:
      openwrt_version: '25.12.5'
      lan_ip: '192.168.1.2'
      rootfs_size: '4G'
    secrets: inherit
